name: Java CI with Maven

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 签出代码
        uses: actions/checkout@v4.2.2

      - name: 设置 JDK
        uses: actions/setup-java@v4.7.0
        with:
          java-version: '11'
          distribution: 'adopt'
          # cache: maven

      - name: 编译并打包
        run: mvn clean package

      - name: 上传构建产物
        uses: actions/upload-artifact@v4.6.1
        with:
          name: Lexical-analysis-Group10
          path: target/*.jar
          retention-days: 7
