name: Java CI with Maven

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置 Java 版本
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: 编译并打包
        run: mvn clean package

      - name: 上传构建产物
        uses: actions/upload-artifact@v2
        with:
          name: my-java-app
          path: target/*.jar
